graphhopper:
  import.osm.ignored_highways: footway,cycleway,path,pedestrian,steps,bridleway
  graph.encoded_values: max_height, max_weight, max_axle_load, max_width, max_length, hgv, road_class, road_environment, surface, hazmat, toll
  datareader.file: indonesia-latest.osm.pbf
  graph.dataaccess: RAM_STORE
  graph.location: graph-cache

  profiles:
    - name: truck_small
      weighting: custom
      custom_model_files: [truck_small.json]

    - name: truck_medium
      weighting: custom
      custom_model_files: [truck_medium.json]

    - name: truck_large
      weighting: custom
      custom_model_files: [truck_large.json]

  profiles_ch:
    - profile: truck_small
    - profile: truck_medium
    - profile: truck_large

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
